export const darkTheme = {
  bg: "#111009", bg2: "#1C1A13", bg3: "#242118",
  text: "#F2EDE4", textMuted: "#6B6655", textDim: "#3A3828",
  accent: "#C8913A", accentDim: "#2A2007",
  border: "#2A2820",
};

export const lightTheme = {
  bg: "#F7F4EF", bg2: "#FFFFFF", bg3: "#F0EBE3",
  text: "#1C1A13", textMuted: "#8A836F", textDim: "#C5BCAD",
  accent: "#B07D2A", accentDim: "#F0E6D0",
  border: "#DDD8CE",
};

export const makeStyles = (t) => ({
  app: { width: "100%", maxWidth: 430, margin: "0 auto", background: t.bg, minHeight: "100vh", fontFamily: "'Outfit', sans-serif", color: t.text, paddingBottom: 32, boxSizing: "border-box" },
  globalBg: { background: t.bg, minHeight: "100vh", width: "100%" },
  header: { padding: "52px 26px 24px", borderBottom: `1px solid ${t.border}` },
  backRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 20 },
  backArrow: { fontSize: 18, color: t.accent, lineHeight: 1, cursor: "pointer" },
  backLabel: { fontSize: 12, color: t.textMuted, fontWeight: 300, cursor: "pointer" },
  pageTitle: { fontFamily: "'Libre Baskerville', serif", fontSize: 34, fontWeight: 400, fontStyle: "italic", color: t.text, letterSpacing: -0.5, lineHeight: 1 },
  pageSub: { marginTop: 6, fontSize: 13, fontWeight: 300, color: t.textMuted },
  logo: { fontFamily: "'Libre Baskerville', serif", fontSize: 44, fontWeight: 400, fontStyle: "italic", color: t.text, letterSpacing: -1, lineHeight: 1 },
  logoEm: { color: t.accent, fontStyle: "italic" },
  tagline: { marginTop: 8, fontSize: 13, fontWeight: 300, color: t.textMuted },
  section: { padding: "24px 26px 0" },
  sectionRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 14 },
  sectionTitle: { fontFamily: "'Libre Baskerville', serif", fontSize: 17, fontStyle: "italic", color: t.text },
  seeAll: { fontSize: 12, color: t.accent, fontWeight: 300, cursor: "pointer" },
  tabsScroll: { display: "flex", gap: 20, overflowX: "auto", scrollbarWidth: "none", borderBottom: `1px solid ${t.border}`, paddingBottom: 0 },
  tab: (active) => ({ flexShrink: 0, fontSize: 13, fontWeight: active ? 500 : 400, color: active ? t.text : t.textMuted, whiteSpace: "nowrap", paddingBottom: 10, borderBottom: active ? `2px solid ${t.accent}` : "2px solid transparent", marginBottom: -1, cursor: "pointer" }),
  recipesScroll: { display: "flex", gap: 12, overflowX: "auto", scrollbarWidth: "none", paddingBottom: 4 },
  recipeCard: { flexShrink: 0, width: 148, background: t.bg2, borderRadius: 16, border: `1px solid ${t.border}`, overflow: "hidden", cursor: "pointer" },
  recipeImg: { width: "100%", height: 108, objectFit: "cover", display: "block" },
  recipeBody: { padding: 12 },
  recipeLabel: { fontSize: 9, letterSpacing: 1.5, textTransform: "uppercase", color: t.accent, marginBottom: 3 },
  recipeName: { fontFamily: "'Libre Baskerville', serif", fontSize: 15, color: t.text, marginBottom: 3 },
  filterRow: { display: "flex", gap: 8, padding: "18px 26px", borderBottom: `1px solid ${t.border}`, overflowX: "auto", scrollbarWidth: "none" },
  filterChip: (active) => ({ flexShrink: 0, padding: "7px 16px", borderRadius: 99, fontSize: 12, fontWeight: 400, border: `1px solid ${active ? t.accent : t.border}`, color: active ? t.accent : t.textMuted, background: "transparent", whiteSpace: "nowrap", cursor: "pointer" }),
  countRow: { padding: "14px 26px 0", fontSize: 11, color: t.textMuted, fontWeight: 300, letterSpacing: 0.3 },
  cards: { padding: "14px 26px 0", display: "flex", flexDirection: "column", gap: 16 },
  bigCard: { borderRadius: 20, overflow: "hidden", background: t.bg2, border: `1px solid ${t.border}`, cursor: "pointer" },
  bigCardImg: { width: "100%", height: 180, objectFit: "cover", display: "block" },
  imgWrap: { position: "relative" },
  badge: { position: "absolute", top: 14, right: 14, background: "rgba(0,0,0,0.55)", borderRadius: 99, padding: "5px 12px", fontSize: 10, color: "#F2EDE4", letterSpacing: 0.8, textTransform: "uppercase" },
  bigCardBody: { padding: "10px 18px 20px", display: "flex", justifyContent: "space-between", alignItems: "flex-end" },
  bigCardLabel: { fontSize: 9, letterSpacing: 1.5, textTransform: "uppercase", color: t.accent, marginBottom: 4 },
  bigCardName: { fontFamily: "'Libre Baskerville', serif", fontSize: 22, fontWeight: 400, fontStyle: "italic", color: t.text, lineHeight: 1.1 },
  bigCardRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8 },
  bigCardTime: { fontSize: 11, color: t.textMuted, fontWeight: 300 },
  goBtn: { width: 36, height: 36, borderRadius: "50%", border: `1px solid ${t.border}`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, color: t.accent },
  heroRow: { display: "flex", gap: 16, alignItems: "flex-start" },
  heroImgWrap: { flexShrink: 0, width: 90, height: 90, borderRadius: 16, overflow: "hidden", border: `1px solid ${t.border}` },
  heroImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  heroText: { flex: 1, paddingTop: 4 },
  heroLabel: { fontSize: 9, letterSpacing: 1.5, textTransform: "uppercase", color: t.accent, marginBottom: 5 },
  heroName: { fontFamily: "'Libre Baskerville', serif", fontSize: 28, fontWeight: 400, fontStyle: "italic", color: t.text, lineHeight: 1.1, marginBottom: 8 },
  heroTags: { display: "flex", gap: 6, flexWrap: "wrap" },
  heroTag: { padding: "4px 10px", borderRadius: 99, border: `1px solid ${t.border}`, fontSize: 10, color: t.textMuted, fontWeight: 300 },
  statStrip: { display: "flex", margin: "24px 26px 0", background: t.bg2, borderRadius: 14, border: `1px solid ${t.border}`, overflow: "hidden" },
  statItem: (last) => ({ flex: 1, padding: "14px 0", display: "flex", flexDirection: "column", alignItems: "center", gap: 4, borderRight: last ? "none" : `1px solid ${t.border}` }),
  statVal: { fontSize: 16, fontWeight: 500, color: t.text },
  statLabel: { fontSize: 10, color: t.textMuted, fontWeight: 300, letterSpacing: 0.3 },
  ingredientRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", background: t.bg2, borderRadius: 12, border: `1px solid ${t.border}`, marginBottom: 6 },
  ingredientName: { fontSize: 14, color: t.text, fontWeight: 400 },
  ingredientAmt: { fontSize: 13, color: t.accent, fontWeight: 500 },
  steps: { display: "flex", flexDirection: "column", gap: 0 },
  stepRow: { display: "flex", gap: 14, alignItems: "flex-start" },
  stepNumWrap: { flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "center" },
  stepNum: { width: 28, height: 28, borderRadius: "50%", background: t.accent, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 500, color: "#111009", flexShrink: 0 },
  stepLine: { width: 1, flex: 1, minHeight: 20, background: t.border, margin: "4px 0" },
  stepBody: { flex: 1, paddingBottom: 16 },
  stepTitle: { fontSize: 13, fontWeight: 500, color: t.text, marginBottom: 3 },
  stepDesc: { fontSize: 12, color: t.textMuted, fontWeight: 300, lineHeight: 1.6 },
  tipsCard: { background: t.bg3, border: `1px solid ${t.border}`, borderRadius: 16, padding: 18, display: "flex", gap: 14, alignItems: "flex-start" },
  tipsIcon: { fontSize: 20, flexShrink: 0, marginTop: 2 },
  tipsTitle: { fontSize: 13, fontWeight: 500, color: t.accent, marginBottom: 5 },
  tipsBody: { fontSize: 12, color: t.textMuted, fontWeight: 300, lineHeight: 1.6 },
  saveBtn: { margin: "24px 26px 0", width: "calc(100% - 52px)", padding: 16, background: t.accent, color: "#111009", border: "none", borderRadius: 14, fontFamily: "'Outfit', sans-serif", fontSize: 14, fontWeight: 500, letterSpacing: 0.3, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, cursor: "pointer" },
  grindCard: { background: t.bg2, border: `1px solid ${t.border}`, borderRadius: 14, padding: "16px 18px" },
  grindTrack: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 3, marginBottom: 10 },
  grindBar: (active) => ({ flex: 1, borderRadius: "3px 3px 0 0", background: active ? t.accent : t.border }),
  grindLabels: { display: "flex", justifyContent: "space-between" },
  grindLabel: (active) => ({ fontSize: 10, color: active ? t.accent : t.textMuted, fontWeight: active ? 500 : 300 }),
  specRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", background: t.bg2, borderRadius: 12, border: `1px solid ${t.border}`, marginBottom: 6 },
  specName: { fontSize: 14, color: t.text, fontWeight: 400 },
  specVal: { fontSize: 13, color: t.accent, fontWeight: 500 },
  settingGroup: { background: t.bg2, border: `1px solid ${t.border}`, borderRadius: 16, overflow: "hidden" },
  settingRow: (last) => ({ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 18px", borderBottom: last ? "none" : `1px solid ${t.border}` }),
  settingName: { fontSize: 14, fontWeight: 400, color: t.text, marginBottom: 2 },
  settingDesc: { fontSize: 11, color: t.textMuted, fontWeight: 300 },
  toggleWrap: { display: "flex", background: t.bg3, borderRadius: 99, border: `1px solid ${t.border}`, overflow: "hidden" },
  toggleOpt: (active) => ({ padding: "7px 16px", fontSize: 12, fontWeight: active ? 500 : 400, color: active ? "#111009" : t.textMuted, background: active ? t.accent : "transparent", borderRadius: 99, cursor: "pointer" }),
  aboutGroup: { background: t.bg2, border: `1px solid ${t.border}`, borderRadius: 16, overflow: "hidden" },
  aboutRow: (last) => ({ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 18px", borderBottom: last ? "none" : `1px solid ${t.border}`, cursor: "pointer" }),
  aboutName: { fontSize: 14, color: t.text, fontWeight: 400 },
  aboutArrow: { fontSize: 14, color: t.textMuted },
  version: { textAlign: "center", marginTop: 32, fontSize: 11, color: t.textMuted, fontWeight: 300, letterSpacing: 0.5 },
  versionSpan: { fontFamily: "'Libre Baskerville', serif", fontStyle: "italic", color: t.accent },
  navBar: { display: "flex", justifyContent: "space-around", alignItems: "center", padding: "24px 20px 32px", marginTop: 28, background: "transparent" },
  navItem: (active) => ({ display: "flex", flexDirection: "column", alignItems: "center", gap: 6, fontSize: 10, fontWeight: 500, letterSpacing: 0.5, color: active ? t.text : t.textMuted, textTransform: "uppercase", cursor: "pointer" }),
  navLine: (active) => ({ width: 22, height: 3, borderRadius: 2, background: "currentColor", opacity: active ? 1 : 0.2 }),
  methodSelect: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: t.accent, fontWeight: 400, cursor: "pointer" },
});
